[Appearance]
style=Breeze
icon_theme=Graphite
custom_palette=true
color_scheme_path=~/.config/qt6ct/colors/Graphite.conf
standard_dialogs=default

[Fonts]
general="Barlow,13,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,,0,0"
fixed="JetBrainsMono Nerd Font Mono,13,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,,0,0"

[Interface]
activate_item_on_single_click=0
buttonbox_layout=0
dialog_buttons_have_icons=1
menus_have_icons=true
toolbutton_style=0
underline_shortcut=1
